'use strict';

/**
 * @ngInject
 */
function Index($scope, Logger) {
  Logger.debug('Index');
  // ViewModel
  var vm = $scope.vm = this;

  vm.welcomeMessage = 'Welcome message generated by AngularJS';
}

module.exports = Index;
